apiVersion: v1
kind: Service
metadata:
  name: nodejs-loadbalancer
  namespace: aplicacion-unir-grupal
spec:
  type: LoadBalancer
  ports:
  - port: 30000
    targetPort: 3000
    protocol: TCP
  selector:
    app: nodejs-app
