apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: aplicacion-unir-grupal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: alex95mf/nodejs-mongodb-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/mydatabase"
